parameters:
  lrotherfield.notify.js: true
  lrotherfield.notify.css: true

services:
  lrotherfield.notify:
    class: LRotherfield\Bundle\NotificationBundle\Notification\Notifications
    arguments: [@session]

  lrotherfield.twig.message_extension:
      class: LRotherfield\Bundle\NotificationBundle\Twig\NotificationExtension
      arguments: [@service_container]
      tags:
          - { name: twig.extension }