services:
  lrotherfield.message:
    class: LRotherfield\Bundle\NotificationBundle\Notification\Message
    arguments: [@session]

  lrotherfield.twig.message_extension:
      class: LRotherfield\Bundle\NotificationBundle\Twig\NotificationExtension
      arguments: [@service_container]
      tags:
          - { name: twig.extension }